In [1]:
import pandas as pd

Dataset1 = pd.read_csv('data/Train_clinical.txt', sep="\t")
Dataset2 = pd.read_csv('data/Train_call.txt', sep="\t", header=None)

dataset_2 = Dataset2[1:].T[4:]
df_concat = pd.concat([Dataset1, dataset_2.reset_index(drop=True)], axis=1)

with open("data/BITM_Cancer_dataset.csv", 'w') as f:
    f.write(df_concat.to_csv(header = False, index = False, sep='\t'))

Dataset3 = pd.read_csv('data/BITM_Cancer_dataset.csv', sep="\t", header=None)
Dataset3

,0,1,2,3,4,5,6,7,8,9,...,2826,2827,2828,2829,2830,2831,2832,2833,2834,2835
0,Array.129,HER2+,0,0,0,0,0,0,0,0,...,2,2,2,2,0,1,1,1,1,1
1,Array.34,HR+,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
2,Array.67,HR+,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
3,Array.24,Triple Neg,0,0,0,0,0,0,0,-1,...,0,0,0,0,0,0,0,0,0,0
4,Array.22,Triple Neg,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
5,Array.36,HR+,0,0,0,0,0,0,0,0,...,1,1,0,1,1,1,1,1,1,1
6,Array.49,HER2+,0,0,0,0,0,0,0,0,...,2,1,1,1,1,1,1,1,1,1
7,Array.16,HER2+,0,0,0,0,-1,0,0,0,...,1,1,1,1,1,1,1,1,1,1
8,Array.146,Triple Neg,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
9,Array.143,HER2+,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
10,Array.65,HR+,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,2,2,2,2
11,Array.62,Triple Neg,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,0,1
12,Array.4,HER2+,-1,-1,-1,-1,-1,-1,-1,-1,...,1,1,1,1,1,1,1,1,1,1
13,Array.76,HER2+,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
14,Array.118,Triple Neg,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
15,Array.154,Triple Neg,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,Array.48,HR+,1,0,0,0,0,0,1,0,...,1,1,1,1,0,1,1,1,1,1
17,Array.6,HER2+,0,0,0,0,0,0,0,0,...,1,1,0,1,1,1,1,1,1,1
18,Array.39,HR+,-1,-1,-1,-1,-1,-1,-1,-1,...,1,1,0,1,1,1,1,1,1,1
19,Array.86,HR+,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
20,Array.112,Triple Neg,0,0,0,0,0,0,0,0,...,2,2,2,2,2,2,2,2,2,2
21,Array.79,HER2+,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
22,Array.124,HR+,0,0,0,0,0,0,0,0,...,2,1,1,1,1,1,1,2,2,2
23,Array.19,HER2+,0,0,0,0,0,0,0,0,...,1,1,1,1,2,1,1,1,2,1
24,Array.27,HR+,0,0,0,0,0,0,0,0,...,1,1,0,1,1,1,1,1,1,1
25,Array.106,HER2+,0,0,0,0,0,0,0,0,...,2,2,2,2,2,2,2,2,2,1
26,Array.110,HER2+,0,0,0,0,0,0,0,0,...,2,2,2,2,2,2,2,2,2,2
27,Array.69,Triple Neg,1,0,0,0,0,0,0,1,...,1,1,1,1,1,1,1,1,1,1
28,Array.73,HER2+,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
29,Array.95,HR+,1,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,Array.75,HER2+,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
71,Array.139,HER2+,0,0,0,0,0,0,0,0,...,1,1,1,1,2,1,1,1,1,1
72,Array.2,HR+,1,1,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
73,Array.117,HR+,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
74,Array.60,HR+,0,0,0,0,0,0,0,-1,...,1,1,1,1,1,1,1,1,1,1
75,Array.38,Triple Neg,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
76,Array.72,HER2+,1,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
77,Array.104,Triple Neg,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
78,Array.137,HR+,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
79,Array.145,Triple Neg,-1,-1,-1,-1,-1,-1,-1,-1,...,1,1,1,1,1,1,1,1,1,0
80,Array.31,Triple Neg,1,1,1,1,1,1,1,1,...,2,2,2,2,2,2,2,2,2,2
81,Array.135,Triple Neg,0,0,0,0,0,0,0,0,...,2,2,2,2,2,2,2,2,2,2
82,Array.111,Triple Neg,1,1,1,1,1,1,1,0,...,1,1,1,1,1,1,1,1,1,1
83,Array.7,HR+,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
84,Array.21,HER2+,0,0,0,0,0,0,0,-1,...,2,2,2,2,2,2,2,2,2,2
85,Array.53,HER2+,0,0,0,0,0,0,0,0,...,2,2,2,2,2,2,2,2,2,2
86,Array.59,HR+,-1,-1,-1,-1,-1,-1,-1,-1,...,0,0,0,0,0,0,0,0,0,0
87,Array.71,Triple Neg,0,0,1,1,1,1,1,0,...,1,1,1,1,1,1,1,1,1,1
88,Array.47,Triple Neg,0,0,0,0,0,0,0,0,...,2,2,1,2,2,2,2,2,2,2
89,Array.107,Triple Neg,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
90,Array.64,Triple Neg,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,2,2,2,2
91,Array.89,HR+,0,0,0,1,1,0,0,0,...,1,1,1,1,1,1,1,1,1,1
92,Array.30,Triple Neg,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
93,Array.35,HR+,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
94,Array.93,Triple Neg,0,0,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
95,Array.10,HER2+,0,0,0,0,0,0,0,0,...,1,1,0,1,1,1,1,1,1,1
96,Array.123,HR+,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
97,Array.100,HR+,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
98,Array.134,HR+,-1,-1,-1,-1,-1,-1,-1,-1,...,1,1,1,1,1,1,1,1,1,1
99,Array.130,HER2+,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1